name: Integration #title

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3 #a github repository to perform checkout to the branch we are working
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # github repository to perform setup for our server
        with:
          node-version: ${{ matrix.node-version }} # versions our steps are going to run for, described in strategy
          cache: 'npm'
      - run: npm i
      - run: npm run test
